name: Publish to PyPI

on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  z
      - name: Build and publish to PyPI
        run: |
          python setup.py sdist bdist_wheel
          pip install twine
          twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: pypi-AgEIcHlwaS5vcmcCJGVkNTJiNDhiLTRhZWEtNDUwZS05YzNlLThjYWYzZmJhYjM1MQACKlszLCJmZjcwYmUzMi00YTQ5LTQ5MjItOWMzYS04OWQ2MGZiNDYzOTQiXQAABiDO8ei1z6c-Kb8R8TGDDOF06ez_5tbV2Ca1zzNcRWqNPQ
